# Tomcat
server.port: 8080

## Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
#logging:
#    level:
#        org.hibernate: WARN
#        org.springframework: WARN
#    file: rooster-mr.log

# Spring settings
spring:
    profiles.active: master
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/{yourDB}?characterEncoding=utf8
        username: {username}
        password: {pasword}
    jpa:
        show-sql: true
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

aliyun:
    accountId: {accountId}
    accessKeyId: {accessKeyId}
    accessKeySecret: {accessKeySecret}
    OTS:
        endpoint: http://rooster-dev.cn-hangzhou.ots-internal.aliyuncs.com
        instance: rooster-dev
